In [4]:
import numpy as np
a=np.random.rand(5,2,4)
type(a)
a

array([[[0.61143497, 0.11588049, 0.3664749 , 0.19526403],
        [0.55036978, 0.74544664, 0.22036459, 0.91252201]],

       [[0.32598596, 0.88402146, 0.46465869, 0.58883143],
        [0.28521295, 0.48742115, 0.26963362, 0.43340438]],

       [[0.83476022, 0.81932484, 0.0266499 , 0.7566527 ],
        [0.53413796, 0.43467563, 0.43810546, 0.43233572]],

       [[0.24046781, 0.74800994, 0.79897691, 0.52617149],
        [0.68295863, 0.07503643, 0.33565769, 0.81268539]],

       [[0.23615662, 0.45600673, 0.43021362, 0.30708808],
        [0.45012661, 0.113277  , 0.07026228, 0.57810206]]])

In [5]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [6]:
np.arange(6) .reshape(1,2,3)

array([[[0, 1, 2],
        [3, 4, 5]]])

In [46]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

#url=urlopen('https://music.bugs.co.kr/chart/album/day/total')
#soup=BeautifulSoup(url.read(),'html.parser')
#musics=soup.find_all('div','albumTitle')
#m=musics.find_all('title')
#m
#for i, music in enumerate(musics):
    #print('{0}:{1}'.format(i+1,music.input['title']))
#    print(ｍusic['title'])
#m=musics[0]
#type(m)
#m.find('title').text

AttributeError: ResultSet object has no attribute 'find_all'. You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?

In [55]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

url = urlopen('https://music.bugs.co.kr/chart/album/day/total')
soup = BeautifulSoup(url.read(), 'html.parser')

musics = soup.find_all('div', 'albumTitle')
i=1
for music in musics:
    title = music.find('a').text
    print('{0}rank: {1}'.format(i,title))
    i+=1

1rank: I've IVE
2rank: NewJeans 1st EP 'New Jeans'
3rank: expérgo
4rank: ANTIFRAGILE
5rank: BORN PINK
6rank: H1-KEY 1st Mini Album [Rose Blossom]
7rank: YOUNHA 6th Album Repackage 'END THEORY : Final Edition'
8rank: WHERE DOES SASQUATCH LIVE? PART 1
9rank: Nine Track Mind (Deluxe Edition)
10rank: BOYS PLANET - ARTIST BATTLE
11rank: YOUNHA 6th Album 'END THEORY'
12rank: FACE
13rank: The Book of Us : Gravity
14rank: FEARLESS
15rank: DIFF
16rank: THE FIFTY
17rank: Candy - Winter Special Mini Album
18rank: Justice
19rank: I NEVER DIE
20rank: 쇼미더머니 11 Episode 3
21rank: IU 5th Album 'LILAC'
22rank: 스트릿 맨 파이터(SMF) Original Vol.3 (계급미션)
23rank: 조각집
24rank: Remember Archive
25rank: I love
26rank: Girls - The 2nd Mini Album
27rank: 버스커 버스커 1집
28rank: MOVE AGAIN
29rank: 전설
30rank: INVU - The 3rd Album
31rank: 공명
32rank: 미스터트롯2 라이벌 매치 베스트 PART1
33rank: Eric Clapton's Crossroads Guitar Festival 2019 (Live)
34rank: IM HERO
35rank: Seoul
36rank: ‘The ReVe Festival 2022 - Feel My Rhythm’
37rank: FIVE 

In [39]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

url=urlopen('https://music.bugs.co.kr/chart/track/realtime/total')
soup=BeautifulSoup(url.read(),'html.parser')
musics=soup.find_all('td','check')
for i,a in enumerate(musics):
    print('{}위: {}'.format(i+1,a.input['title']))

0위: I AM
1위: Kitsch
2위: 꽃
3위: Cupid
4위: Ditto
5위: Hype Boy
6위: Teddy Bear
7위: OMG
8위: Love Me Like This
9위: 건물 사이에 피어난 장미 (Rose Blossom)
10위: I Don’t Think That I Like Her
11위: Attention
12위: After LIKE
13위: CHRISTIAN
14위: 파이팅 해야지 (Feat. 이영지)
15위: 사건의 지평선
16위: LOVE DIVE
17위: ANTIFRAGILE
18위: 심(心)
19위: Dangerously
20위: 밤이 무서워요 (Lonely Night)
21위: Poppy (Korean Ver.)
22위: 한 페이지가 될 수 있게
23위: 오르트구름
24위: When I Get Old
25위: VIBE (feat. Jimin of BTS)
26위: Shut Down
27위: Cupid (Twin Ver.)
28위: FEARLESS
29위: 사랑인가 봐
30위: Candy
31위: ELEVEN
32위: Cookie
33위: That's Hilarious
34위: Nostalgia
35위: 너의 모든 순간
36위: Pink Venom
37위: WHEN I MOVE
38위: 그라데이션
39위: 정이라고 하자 (Feat. 10CM)
40위: Nxde
41위: Unholy
42위: Say I Love You
43위: Blue Blood
44위: STAY
45위: Young, Dumb, Stupid
46위: Love story
47위: 다정히 내 이름을 부르면
48위: 사람 Pt.2 (feat. 아이유)
49위: 자격지심 (Feat. ZICO)
50위: Left and Right (Feat. Jung Kook of BTS)
51위: Off My Face
52위: 내가 아니라도
53위: Impurities
54위: Rush Hour (Feat. j-hope of BTS)
55위: 모든 날, 모든 순간 (Every day